### ISSUE TITLE
/data decryption is not working on Oreo+

### ISSUE THREAD

**Issue by nadiamoe** [TeamWin/android_device_htc_hima#2] opened 2018-05-11 15:54 UTC
Tested with AICP (Oreo) and three different encryption methods (4x4 pattern, 3x3 pattern, PIN)

Seems like other branches of TWRP already got a hotfix for this issue. Are there any possibility of getting it ported to hima?

**Comment by CaptainThrowback** [comment] 2018-05-12 14:40
Well since the M9 doesn't have an official Oreo release, there was no need to update it. I'm not sure what decryption methods the custom ROMs are using. Right now my M9 is being repaired, but once I have it back, I'll flash one of these custom ROMs and see if the fix from the newer device trees works here. So you'll have to wait a bit and either live without decryption in TWRP, or run unencrypted in the meantime.

**Comment by nadiamoe** [comment] 2018-05-12 18:03
Decrypting /data on recovery is convenient but not that critical. I just put zips to flash under /system and ready to go :P

Nice to hear you will give it a look, thanks for the hard work :D

**Comment by CaptainThrowback** [comment] 2018-05-12 22:24
FYI - You can still install zips in TWRP from the SD card - having /data decrypted isn't necessary to do that.

**Comment by nadiamoe** [comment] 2018-05-14 12:58
I don't trust sdcard, they corrupt just too easily (already happened to me with this phone once, in fact), so I don't have one at the moment. Also having personal data in plaintext (e.g. pictures) kind of defeats the purpose of encryption :P

Anyway, thanks for the advice :)

**Comment by Claymore1297** [comment] 2018-06-10 22:10
[recovery.log](https://github.com/TeamWin/android_device_htc_hima/files/2088273/recovery.log)
Issue happens on sw-and hw encryption. I've activated ZRAM in ROM, perhaps this causes this issue.
Issue affects LOS 15.1 too.

**Comment by CaptainThrowback** [comment] 2018-06-10 23:08
Zram has nothing to do with encryption. Like I already said, once I have my M9 back, I'll look into it. Hopefully it'll be here next week.

**Comment by CaptainThrowback** [comment] 2018-06-11 17:19
I don't have my device yet, but my build box is on, so I'm creating a test build using the kernel from @Claymore1297's latest LineageOS 15.1 build, and the updated device tree patches. I'm not sure if that kernel will boot on the device or not. I noticed that the dtb is separated in that boot.img, even though it's been combined on the latest stock ROM for the device. That shouldn't cause an issue, but the fact that I'm using an Oreo kernel in a 6.0 tree might be problematic. If you'd like to test, stay tuned, and I'll link the build here (if it's successful).

**Comment by Claymore1297** [comment] 2018-06-11 17:33
@CaptainThrowback I will test this instantly, as soon you link your build.

**Comment by CaptainThrowback** [comment] 2018-06-11 17:37
@Claymore1297 https://drive.google.com/open?id=1gcW6Bb1x_DQKepGrsGhFlq4xX1kTQ78v

Give it a try and let me know what happens.

**EDIT:** I just realized I missed some files. Need to build again, sorry! You can let me know if that one at least boots, though.

**Comment by Claymore1297** [comment] 2018-06-11 18:08
it boots, but while encrypt, it gets a timeout.
[recovery.log](https://github.com/TeamWin/android_device_htc_hima/files/2091168/recovery.log)

**Comment by CaptainThrowback** [comment] 2018-06-11 18:19
@Claymore1297 

It booting is a good sign. I'm hoping it's just the missing files that are preventing qseecomd from starting. Here's an updated build with the missing files included. Let me know if this one is any different. Thanks!

https://drive.google.com/open?id=1iAVG3nStkX5TMmpDE97MT9BhlCCnU8iV

**Comment by Claymore1297** [comment] 2018-06-11 18:35
no timeout, but it seems, that vendor qseecomd couldn't start. Log attached.
[recovery.log](https://github.com/TeamWin/android_device_htc_hima/files/2091253/recovery.log)

**Comment by CaptainThrowback** [comment] 2018-06-11 18:44
It's probably because the qseecomd service in Lineage is patched to remove the HTC liblog dependency. I think there are some shims that need to be included for the service to run properly. I'll have to see what I can find in the ROM. I'll work on it more once I have a device in hand and can test directly.

**Comment by Claymore1297** [comment] 2018-06-11 18:50
Oh yes, of course.
Maybe is this helpful:
https://review.lineageos.org/#/c/LineageOS/android_device_htc_hiae/+/214993/

**Comment by CaptainThrowback** [comment] 2018-06-11 21:20
Thanks for the link, @Claymore1297! That was quite helpful. I've made one last build, if you'd like to try it. I'm not sure if it'll work, but I added the preload for the liblog, so it's possible it'll work now. Though I don't know that the vendor qseecomd will actual use it. If this doesn't work, it'll have to wait until I have my device in hand. Thanks for all of your assistance and testing so far.

https://drive.google.com/open?id=1hjjK8yTMMazbyFQQIH10SR1Vhk9qHXi7

**Comment by Claymore1297** [comment] 2018-06-11 22:06
Sadly it didn't work.
with this commands, I get vendor qseecomd running and this output (maybe it helps a bit):
export LD_PRELOAD=/sbin/liblog_htc_sbin.so
export LD_LIBRARY_PATH=/system/vendor/lib64:/system/vendor/lib
/system/vendor/bin/qseecomd
libc: Using old property service protocol ("ro.property_service.version" is not set)
libc: Property service has timed out while trying to set "sys.qseecomd.stage" to "5"
libc: Property service has timed out while trying to set "sys.keymaster.loaded" to "true"

Thank you, for your help!

**Comment by CaptainThrowback** [comment] 2018-06-12 00:35
Where's the recovery log from the last build? Can you grab dmesg as well? That'll give me a good starting point for when I have my M9 back. Thanks.

**Comment by Claymore1297** [comment] 2018-06-12 06:04
here it is
[dmesg.txt](https://github.com/TeamWin/android_device_htc_hima/files/2092736/dmesg.txt)
[recovery.log](https://github.com/TeamWin/android_device_htc_hima/files/2092738/recovery.log)

**Comment by CaptainThrowback** [comment] 2018-06-12 15:47
Alright, last try (for now). This *should* work, since both of those exports should now be getting set as part of the ven_qseecomd service. Assuming that service does run, I still don't know if decrypt will be successful, but with all of those services running, there's no reason it shouldn't (stranger things have happened, though).

https://drive.google.com/open?id=1Kol3eluCjdYb_TlMB_qvCpq3V83Q8vKL

**Comment by Claymore1297** [comment] 2018-06-12 19:12
it didn't work, but today I got no time to look behind the szene... logs attached.
It just don't start the vendor qseecomd ...
[dmesg.txt](https://github.com/TeamWin/android_device_htc_hima/files/2095486/dmesg.txt)
[recovery.log](https://github.com/TeamWin/android_device_htc_hima/files/2095487/recovery.log)

**Comment by CaptainThrowback** [comment] 2018-06-12 20:09
Thanks for the logs, @Claymore1297. The dmesg seems to be upset about the missing seclabel for ven_qseecomd.

`<11>[   15.747980] c2      1 init: could not get context while starting 'ven_qseecomd'`

Going to try assigning it to the vold domain and see if that gets it running. I'll upload another one, in case you or someone else wants to test. My M9 is on its way back to me now, so if we can't get this figured out before I have it, I can start doing some intensive local testing once it's back in my hands.

https://drive.google.com/open?id=16k0AlNFhd5LqVQdsq1GSlvNxfFRuEwoK

**Comment by Claymore1297** [comment] 2018-06-13 05:56
it seems, there are more SELinux denials.
Logs attached, thanks for your efforts!
[dmesg.txt](https://github.com/TeamWin/android_device_htc_hima/files/2096759/dmesg.txt)
[recovery.log](https://github.com/TeamWin/android_device_htc_hima/files/2096760/recovery.log)

**Comment by CaptainThrowback** [comment] 2018-06-13 12:41
Well, the ven_qseecomd service is now starting, vold gets connected, but the password still shows up as wrong and decrypt fails. So that means the issue is elsewhere. Once I have my M9, I'll enable the debug flags and dig deeper into it. At this point, everything seems to be working as it should, so I don't know why it's not working. I'm not sure if the denials you mention are relevant, as I think they're just referring to the old property service, which shouldn't be an issue. Thanks for all your testing and help @Claymore1297

**Comment by Claymore1297** [comment] 2018-06-13 12:59
you might be right, I just saw this, but hadn't time to look deeper in it this morning.
Please let me know, if I can do something for you.

**Comment by CaptainThrowback** [comment] 2018-07-02 18:08
Well, I have good news and bad news.

The good news is, I was able to build a TWRP that decrypts AOSP Oreo. The bad news is, whether or not decryption works is dependent on whether the build version and security patch level of the image match what system shows. Even if I dynamically update the props in recovery based on what's in system, it seems that the values from the cmdline supersede any props, so there's no real way to make them match before keymaster tries to start. I'm not sure what the best solution is for this, to be honest. This is an issue that exists on all Oreo devices that use FDE. I'm working with @Dees-Troy on this for another device, so if we can figure out a way around it there, then I can apply that same fix here. But I'm not currently hopeful :/.

**Comment by CaptainThrowback** [comment] 2018-07-02 18:34
@Claymore1297 @roobre 
Give this build a try and let me know if decryption works for you. It's working for me.

https://drive.google.com/open?id=1TJZKiAgspJMbU6YemxNhOUFQP9TQiiN%5F

**Comment by Claymore1297** [comment] 2018-07-02 21:09
get an http 404... can you check the link please.
EDIT: sorry, my bad ...

**Comment by CaptainThrowback** [comment] 2018-07-02 21:14
@Claymore1297 make sure you're getting the underscore at the end...

EDIT: Updated it for you.

**Comment by Claymore1297** [comment] 2018-07-03 05:18
@CaptainThrowback - LGTM. Works on LOS 15.1 + AICP 13.1 :-)

**Comment by CaptainThrowback** [comment] 2018-07-03 13:57
@Claymore1297

That's great news. The next official version of TWRP will include this support. That release should be coming in the next few days. In the meantime, you can direct people to the above version. Thanks for testing!

**Comment by Claymore1297** [comment] 2018-07-03 14:04
done. https://forum.xda-developers.com/showpost.php?p=76976647&postcount=253
and thank you! :-)

**Comment by CaptainThrowback** [comment] 2018-07-09 02:00
This issue is resolved with the official 3.2.2-0. Please close.

**Closed as completed** 2018-07-09 09:34 UTC
